drift_correction:
  400: -219.49
  500: -208.08
  600: -216.168
  700: -228.846
encoders:
  left:
    a: 23
    b: 24
  right:
    a: 16
    b: 26
motors:
  left:
    en: 5
    lpwm: 13
    rpwm: 12
  right:
    en: 6
    lpwm: 19
    rpwm: 18
robot_geometry:
  wheel_base_mm: 150
  wheel_diameter_mm: 241
